package dmk.pastebin.model


object PasteTestData{
  
  val paste = """<paste>
<paste_key>vKz5ruMX</paste_key>
<paste_date>1399916371</paste_date>
<paste_title>Isabelita</paste_title>
<paste_size>3292</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/vKz5ruMX</paste_url>
<paste_hits>7874</paste_hits>
</paste>    
    """
    
  val pastes = """<paste>
<paste_key>vKz5ruMX</paste_key>
<paste_date>1399916371</paste_date>
<paste_title>Isabelita</paste_title>
<paste_size>3292</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/vKz5ruMX</paste_url>
<paste_hits>7874</paste_hits>
</paste>
<paste>
<paste_key>xLQxP5PC</paste_key>
<paste_date>1399838646</paste_date>
<paste_title>100 Israel Site's Hacked By Anonymous Tunisia - Part I</paste_title>
<paste_size>4888</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/xLQxP5PC</paste_url>
<paste_hits>2726</paste_hits>
</paste>
<paste>
<paste_key>6MpsigN4</paste_key>
<paste_date>1399741912</paste_date>
<paste_title>Your Anon News - Truth and reconciliation</paste_title>
<paste_size>9543</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/6MpsigN4</paste_url>
<paste_hits>6941</paste_hits>
</paste>
<paste>
<paste_key>5s1QLFDM</paste_key>
<paste_date>1399825374</paste_date>
<paste_title>NSA kills based on metadata.</paste_title>
<paste_size>4084</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/5s1QLFDM</paste_url>
<paste_hits>3249</paste_hits>
</paste>
<paste>
<paste_key>sMSQCZTg</paste_key>
<paste_date>1399848837</paste_date>
<paste_title>Tues 5/13 Occupy Chicago Appeal - 300 arrested 2011</paste_title>
<paste_size>2887</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/sMSQCZTg</paste_url>
<paste_hits>604</paste_hits>
</paste>
<paste>
<paste_key>LVWcQAfz</paste_key>
<paste_date>1399708150</paste_date>
<paste_title>[FREE] Bring UNLIMITED Traffic to your URLs! [Adsense Safe]</paste_title>
<paste_size>2104</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/LVWcQAfz</paste_url>
<paste_hits>8693</paste_hits>
</paste>
<paste>
<paste_key>drwe9i24</paste_key>
<paste_date>1399843101</paste_date>
<paste_title>II Part of Israel Sites (108) Hacked By Anonymous Tunisia</paste_title>
<paste_size>5319</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/drwe9i24</paste_url>
<paste_hits>1368</paste_hits>
</paste>
<paste>
<paste_key>cfnJ7YBR</paste_key>
<paste_date>1399836483</paste_date>
<paste_title>Dunksvc Nike Subdomain Users Leaked By AnonGhost</paste_title>
<paste_size>60666</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/cfnJ7YBR</paste_url>
<paste_hits>888</paste_hits>
</paste>
<paste>
<paste_key>BA9fkDj8</paste_key>
<paste_date>1399970994</paste_date>
<paste_title>#Bloggerverarsche</paste_title>
<paste_size>3619</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/BA9fkDj8</paste_url>
<paste_hits>768</paste_hits>
</paste>
<paste>
<paste_key>4vuJxkYc</paste_key>
<paste_date>1399715077</paste_date>
<paste_title></paste_title>
<paste_size>3316</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/4vuJxkYc</paste_url>
<paste_hits>826</paste_hits>
</paste>
<paste>
<paste_key>zVhw7NvW</paste_key>
<paste_date>1399759562</paste_date>
<paste_title>JOLIET POLICE BRUTALITY</paste_title>
<paste_size>1351</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/zVhw7NvW</paste_url>
<paste_hits>810</paste_hits>
</paste>
<paste>
<paste_key>TjE8sbrJ</paste_key>
<paste_date>1399964896</paste_date>
<paste_title>48 Hour Marathon</paste_title>
<paste_size>3097</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/TjE8sbrJ</paste_url>
<paste_hits>559</paste_hits>
</paste>
<paste>
<paste_key>qLYFJ9QN</paste_key>
<paste_date>1399797267</paste_date>
<paste_title>tributing to the girl who suicide</paste_title>
<paste_size>448</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/qLYFJ9QN</paste_url>
<paste_hits>847</paste_hits>
</paste>
<paste>
<paste_key>ynpScDm3</paste_key>
<paste_date>1399885666</paste_date>
<paste_title></paste_title>
<paste_size>1526</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/ynpScDm3</paste_url>
<paste_hits>772</paste_hits>
</paste>
<paste>
<paste_key>T4KF5aE8</paste_key>
<paste_date>1399869295</paste_date>
<paste_title>Send Yumi Hara Your Fan Messages!</paste_title>
<paste_size>1315</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/T4KF5aE8</paste_url>
<paste_hits>321</paste_hits>
</paste>
<paste>
<paste_key>1sTuJisg</paste_key>
<paste_date>1399861243</paste_date>
<paste_title>THE FUTURE OF WHISTLEBLOWING</paste_title>
<paste_size>1703</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/1sTuJisg</paste_url>
<paste_hits>354</paste_hits>
</paste>
<paste>
<paste_key>1zhL7CB5</paste_key>
<paste_date>1399827829</paste_date>
<paste_title>Massive Anti-Security Data leak by Anonymous Centre</paste_title>
<paste_size>6749</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/1zhL7CB5</paste_url>
<paste_hits>473</paste_hits>
</paste>
<paste>
<paste_key>ieCSJwLW</paste_key>
<paste_date>1399850734</paste_date>
<paste_title>BF4 CTE String dump</paste_title>
<paste_size>6945</paste_size>
<paste_expire_date>0</paste_expire_date>
<paste_private>0</paste_private>
<paste_format_long>None</paste_format_long>
<paste_format_short>text</paste_format_short>
<paste_url>http://pastebin.com/ieCSJwLW</paste_url>
<paste_hits>2101</paste_hits>
</paste>"""
}